-- set the environment abbreviation variable
-- -----------------------------------------
SET ENV_ABBR = 'DEV_';
-- -----------------------------------------

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';

/*
Roles:
- TRANSFORMER (DATA_ENGINEER)
- ANALYST
- DATA_LOADER (for ADF)
- REPORTER (for BI)
    - REPORTER_BILLING (for PBI Direct Query SSO)
    - REPORTER_FINANCE (for PBI Direct Query SSO)
    - REPORTER_MARKETING (for PBI Direct Query SSO)
- IT_GOVERNANCE

*/
-- define environment functional roles and associated warehouses
SET ENV_TRANSFORMER = $ENV_ABBR || 'TRANSFORMER';
SET ENV_TRANSFORMER_WH = $ENV_ABBR || 'TRANSFORMER_WH';

SET ENV_ANALYST = $ENV_ABBR || 'ANALYST';
SET ENV_ANALYST_WH = $ENV_ABBR || 'ANALYST_WH';

SET ENV_DATA_LOADER = $ENV_ABBR || 'DATA_LOADER';
SET ENV_DATA_LOADER_WH = $ENV_ABBR || 'DATA_LOADER_WH';

SET ENV_REPORTER = $ENV_ABBR || 'REPORTER';
SET ENV_REPORTER_WH = $ENV_ABBR || 'REPORTER_WH';

SET ENV_REPORTER_BILLING = $ENV_ABBR || 'REPORTER_BILLING';
SET ENV_REPORTER_BILLING_WH = $ENV_ABBR || 'REPORTER_BILLING_WH';

SET ENV_REPORTER_FINANCE = $ENV_ABBR || 'REPORTER_FINANCE';
SET ENV_REPORTER_FINANCE_WH = $ENV_ABBR || 'REPORTER_FINANCE_WH';

SET ENV_REPORTER_MARKETING = $ENV_ABBR || 'REPORTER_MARKETING';
SET ENV_REPORTER_MARKETING_WH = $ENV_ABBR || 'REPORTER_MARKETING_WH';



SET ENV_IT_GOVERNANCE = $ENV_ABBR || 'IT_GOVERNANCE';
SET ENV_IT_GOVERNANCE_WH = $ENV_ABBR || 'IT_GOVERNANCE_WH';









-- create the DATA_ENGINEER and DATA_ANALYST environment functional roles
USE ROLE IDENTIFIER($ENV_USERADMIN);

CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_TRANSFORMER);
GRANT ROLE IDENTIFIER($ENV_TRANSFORMER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_ANALYST);
GRANT ROLE IDENTIFIER($ENV_ANALYST) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_DATA_LOADER);
GRANT ROLE IDENTIFIER($ENV_DATA_LOADER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_REPORTER);
GRANT ROLE IDENTIFIER($ENV_REPORTER) TO ROLE IDENTIFIER($ENV_SYSADMIN);


CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_REPORTER_BILLING);
GRANT ROLE IDENTIFIER($ENV_REPORTER_BILLING) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_REPORTER_FINANCE);
GRANT ROLE IDENTIFIER($ENV_REPORTER_FINANCE) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_REPORTER_MARKETING);
GRANT ROLE IDENTIFIER($ENV_REPORTER_MARKETING) TO ROLE IDENTIFIER($ENV_SYSADMIN);



CREATE ROLE  IF NOT EXISTS IDENTIFIER($ENV_IT_GOVERNANCE);
GRANT ROLE IDENTIFIER($ENV_IT_GOVERNANCE) TO ROLE IDENTIFIER($ENV_SYSADMIN);





-- create virtual warehouses for each functional role
USE ROLE IDENTIFIER($ENV_SYSADMIN);
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_TRANSFORMER_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_TRANSFORMER_WH) TO ROLE IDENTIFIER($ENV_TRANSFORMER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_ANALYST_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_ANALYST_WH) TO ROLE IDENTIFIER($ENV_ANALYST);


CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_DATA_LOADER_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_DATA_LOADER_WH) TO ROLE IDENTIFIER($ENV_DATA_LOADER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_WH) TO ROLE IDENTIFIER($ENV_REPORTER);


CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_BILLING_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_BILLING_WH) TO ROLE IDENTIFIER($ENV_REPORTER_BILLING);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_FINANCE_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_FINANCE_WH) TO ROLE IDENTIFIER($ENV_REPORTER_FINANCE);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_MARKETING_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_MARKETING_WH) TO ROLE IDENTIFIER($ENV_REPORTER_MARKETING);




CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_IT_GOVERNANCE_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_IT_GOVERNANCE_WH) TO ROLE IDENTIFIER($ENV_IT_GOVERNANCE);