-- ============================================================
-- PLATFORM_DB.RBAC - provisioning procedures
-- RUN ONCE PER ACCOUNT (re-run whole file after any edit).
--
-- Stored procedures used to provision environments:
--   CREATE_DATABASE / DROP_DATABASE - environment databases
--   CREATE_SCHEMA   / DROP_SCHEMA   - schemas + RO/RW/FULL access roles
--
-- EXECUTE AS CALLER: they run with the caller's privileges (e.g.
-- {ENV}_SYSADMIN), so the caller owns the objects created.
-- Requires 02_platform_database.sql (PLATFORM_DB + RBAC) first.
-- ============================================================
USE ROLE SYSADMIN;
USE DATABASE PLATFORM_DB;
USE SCHEMA RBAC;


-- ------------------------------------------------------------
-- CREATE_DATABASE - create a new environment database
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CREATE_DATABASE (database_name VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
  public_schema VARCHAR := database_name || '.PUBLIC';
BEGIN
  CREATE DATABASE IF NOT EXISTS IDENTIFIER(:database_name);
  DROP SCHEMA IF EXISTS IDENTIFIER(:public_schema);
  RETURN 'Success';
END;


-- ------------------------------------------------------------
-- DROP_DATABASE - drop a database only if it has no user schemas
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE DROP_DATABASE (database_name VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
    DB_COUNT INTEGER;
    SCHEMAS_LIST VARIANT;
BEGIN
    -- Check if database exists
    SHOW DATABASES;
    SELECT COUNT(1) INTO DB_COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = :database_name;

    IF (DB_COUNT = 0) THEN
        RETURN 'Database ' || :database_name || ' does not exist or not authorized.';
    END IF;

    -- Check if any schemas exist in the database
    SHOW SCHEMAS IN DATABASE IDENTIFIER (:database_name);

    SELECT ARRAY_AGG("name") INTO SCHEMAS_LIST
    FROM TABLE (RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "name" NOT IN ('INFORMATION_SCHEMA', 'PUBLIC');

    IF (ARRAY_SIZE(SCHEMAS_LIST) > 0) THEN
        RETURN 'Database was not dropped because it contains schemas: ' || ARRAY_TO_STRING(SCHEMAS_LIST);
    END IF;

    DROP DATABASE IDENTIFIER(:database_name);
    RETURN 'Database ' || :database_name || ' was dropped';
END;


-- ------------------------------------------------------------
-- CREATE_SCHEMA - create a schema + RO/RW/FULL access roles
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CREATE_SCHEMA (database_name VARCHAR, schema_name VARCHAR, env_abbr VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
    RO_ROLE := database_name || '.' || schema_name || '_RO_AR';
    RW_ROLE := database_name || '.' || schema_name || '_RW_AR';
    FULL_ROLE := database_name || '.' || schema_name || '_FULL_AR';
    ENV_SYSADMIN_ROLE := env_abbr || 'SYSADMIN';
    QUALIFIED_SCHEMA_NAME := database_name || '.' || schema_name;
    RETURN_MSG VARCHAR := '';
BEGIN
-- create schema
    CREATE SCHEMA IF NOT EXISTS IDENTIFIER(:QUALIFIED_SCHEMA_NAME) WITH MANAGED ACCESS;
    RETURN_MSG := RETURN_MSG || 'Created schema ' || QUALIFIED_SCHEMA_NAME || '; ';

-- create schema access roles
    -- read only
    CREATE DATABASE ROLE IF NOT EXISTS IDENTIFIER(:RO_ROLE);
    RETURN_MSG := RETURN_MSG || 'Created role ' || RO_ROLE || '; ';

    -- read/write
    CREATE DATABASE ROLE IF NOT EXISTS IDENTIFIER(:RW_ROLE);
    RETURN_MSG := RETURN_MSG || 'Created role ' || RW_ROLE || '; ';
    -- grant ro role to rw role to maintain role hierarchy
    GRANT DATABASE ROLE IDENTIFIER(:RO_ROLE) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    -- full access
    CREATE DATABASE ROLE IF NOT EXISTS IDENTIFIER(:FULL_ROLE);
    RETURN_MSG := RETURN_MSG || 'Created role ' || FULL_ROLE || '; ';
    -- grant rw role to full role to maintain role hierarchy
    GRANT DATABASE ROLE IDENTIFIER(:RW_ROLE) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    GRANT DATABASE ROLE IDENTIFIER(:FULL_ROLE) TO ROLE IDENTIFIER(:ENV_SYSADMIN_ROLE);

-- grants to access roles
    -- ro_role
    GRANT USAGE ON SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);

    GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE, READ ON ALL STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON ALL FILE FORMATS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL STREAMS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON ALL PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON ALL FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE STREAMS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);

    -- rw_role
    GRANT USAGE ON SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT INSERT, UPDATE, DELETE, REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT READ, WRITE ON ALL STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON ALL PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON ALL FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT INSERT, UPDATE, DELETE, REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    -- full_role
    GRANT ALL PRIVILEGES ON SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);

    -- do not grant future ownership because it messes up some object types (eg. tasks, dynamic tables, data metric functions, etc.)
    -- use a functional role to create objects

    RETURN RETURN_MSG;
END;


-- ------------------------------------------------------------
-- DROP_SCHEMA - drop a schema and its RO/RW/FULL access roles
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE DROP_SCHEMA (database_name VARCHAR, schema_name VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
    ro_role := database_name || '.' || schema_name || '_RO_AR';
    rw_role := database_name || '.' || schema_name || '_RW_AR';
    full_role := database_name || '.' || schema_name || '_FULL_AR';
    SCHEMA_COUNT INTEGER;
BEGIN
    SHOW SCHEMAS IN DATABASE IDENTIFIER(:database_name);
    SELECT count(1) INTO SCHEMA_COUNT
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "name" = UPPER(:schema_name);

    IF (SCHEMA_COUNT = 0) THEN
        RETURN 'Schema ' || :database_name || '.' || :schema_name || ' does not exist.';
    END IF;

    -- drop schema
    EXECUTE IMMEDIATE 'DROP SCHEMA ' || :database_name || '.' || :schema_name;

    -- drop roles
    DROP DATABASE ROLE IF EXISTS IDENTIFIER(:ro_role);
    DROP DATABASE ROLE IF EXISTS IDENTIFIER(:rw_role);
    DROP DATABASE ROLE IF EXISTS IDENTIFIER(:full_role);

    RETURN 'Schema ' || :database_name || '.' || :schema_name || ' was dropped.';
END;
