-- set the environment abbreviation variable
-- -----------------------------------------
--SET ENV_ABBR = 'DEV_';
SET ENV_ABBR = '';
-- -----------------------------------------

-- PROVISION initialization script
-- creates the following objects in the environment
--   warehouse <ENV>_PROVISION_WH
--   database <ENV>_PROVISION_DB
--   schema RBAC

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';
SET ENV_WH = $ENV_ABBR || 'PROVISION_WH';
SET ENV_DB = $ENV_ABBR || 'PROVISION_DB';

USE ROLE IDENTIFIER($ENV_SYSADMIN);
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS IDENTIFIER($ENV_DB);
DROP SCHEMA IF EXISTS PUBLIC;
CREATE SCHEMA IF NOT EXISTS RBAC WITH MANAGED ACCESS;

USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
-- -------------------------------------------------------------------------
-- Create database procedure - creates a new database within the environment
-- -------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CREATE_DATABASE (database_name VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
BEGIN
  CREATE DATABASE IF NOT EXISTS IDENTIFIER(:database_name);
  DROP SCHEMA IF EXISTS PUBLIC;
  RETURN 'Success';
END;

USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
-- -------------------------------------------------------------------------
-- Drop database procedure - drops the database if it doesn't contain any schemas
-- -------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE DROP_DATABASE (database_name VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
    DB_COUNT INTEGER;
    SCHEMAS_LIST VARIANT;
BEGIN
    -- Check if database exists
    SHOW DATABASES;
    SELECT COUNT(1) INTO DB_COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "name" = :database_name;

    IF (DB_COUNT = 0) THEN
        RETURN 'Database ' || :database_name || ' does not exist or not authorized.';
    END IF;

    -- Check if any schemas exist in the database
    SHOW SCHEMAS IN DATABASE IDENTIFIER (:database_name);

    SELECT ARRAY_AGG("name") INTO SCHEMAS_LIST
    FROM TABLE (RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "name" NOT IN ('INFORMATION_SCHEMA', 'PUBLIC');

    IF (ARRAY_SIZE(SCHEMAS_LIST) > 0) THEN
        RETURN 'Database was not dropped because it contains schemas: ' || ARRAY_TO_STRING(SCHEMAS_LIST);
    END IF;

    DROP DATABASE IDENTIFIER(:database_name);
    RETURN 'Database ' || :database_name || ' was dropped';
END;

USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
-- -------------------------------------------------------------------------
-- Create schema procedure - creates a new schema and access roles within the environment
-- -------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CREATE_SCHEMA (database_name VARCHAR, schema_name VARCHAR, env_abbr VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
    RO_ROLE := database_name || '.' || schema_name || '_RO_AR';
    RW_ROLE := database_name || '.' || schema_name || '_RW_AR';
    FULL_ROLE := database_name || '.' || schema_name || '_FULL_AR';
    ENV_SYSADMIN_ROLE := env_abbr || 'SYSADMIN';
    QUALIFIED_SCHEMA_NAME := database_name || '.' || schema_name;
    RETURN_MSG VARCHAR := '';
BEGIN
-- create schema
    CREATE SCHEMA IF NOT EXISTS IDENTIFIER(:QUALIFIED_SCHEMA_NAME) WITH MANAGED ACCESS;
    RETURN_MSG := RETURN_MSG || 'Created schema ' || QUALIFIED_SCHEMA_NAME || '; ';

-- create schema access roles
    -- read only
    CREATE DATABASE ROLE IF NOT EXISTS IDENTIFIER(:RO_ROLE);
    RETURN_MSG := RETURN_MSG || 'Created role ' || RO_ROLE || '; ';

    -- read/write
    CREATE DATABASE ROLE IF NOT EXISTS IDENTIFIER(:RW_ROLE);
    RETURN_MSG := RETURN_MSG || 'Created role ' || RW_ROLE || '; ';
    -- grant ro role to rw role to maintain role hierarchy
    GRANT DATABASE ROLE IDENTIFIER(:RO_ROLE) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    -- full access
    CREATE DATABASE ROLE IF NOT EXISTS IDENTIFIER(:FULL_ROLE);
    RETURN_MSG := RETURN_MSG || 'Created role ' || FULL_ROLE || '; ';
    -- grant ro role to rw role to maintain role hierarchy
    GRANT DATABASE ROLE IDENTIFIER(:RW_ROLE) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    GRANT DATABASE ROLE IDENTIFIER(:FULL_ROLE) TO ROLE IDENTIFIER(:ENV_SYSADMIN_ROLE);

-- grants to access roles
    -- ro_role
    GRANT USAGE ON SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);

    GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE, READ ON ALL STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON ALL FILE FORMATS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL STREAMS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON ALL PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON ALL FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE STREAMS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);
    GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RO_ROLE);

    -- rw_role
    GRANT USAGE ON SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT INSERT, UPDATE, DELETE, REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);
    GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:RW_ROLE);

    -- full_role
    GRANT ALL PRIVILEGES ON SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);

    -- do not grant future ownership because it messes up some object types (eg. tasks, dynamic tables, data metric functions, etc.)
    -- use a functional role to create objects

    --GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    --GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA IDENTIFIER(:QUALIFIED_SCHEMA_NAME) TO DATABASE ROLE IDENTIFIER(:FULL_ROLE);
    
    RETURN RETURN_MSG;
END;

USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
-- -------------------------------------------------------------------------
-- Drop schema procedure - drops the schema and access roles
-- -------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE DROP_SCHEMA (database_name VARCHAR, schema_name VARCHAR)
RETURNS VARCHAR
EXECUTE AS CALLER
AS
DECLARE
    ro_role := schema_name || '_RO_AR';
    rw_role := schema_name || '_RW_AR';
    full_role := schema_name || '_FULL_AR';
    SCHEMA_COUNT INTEGER;
BEGIN
    SHOW SCHEMAS IN DATABASE IDENTIFIER(:database_name);
    SELECT count(1) INTO SCHEMA_COUNT
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "name" = UPPER(:schema_name);

    IF (SCHEMA_COUNT = 0) THEN
        RETURN 'Schema ' || :database_name || '.' || :schema_name || ' does not exist.';
    END IF;

    -- drop schema
    EXECUTE IMMEDIATE 'DROP SCHEMA ' || :database_name || '.' || :schema_name;

    -- drop roles
    DROP DATABASE ROLE IF EXISTS IDENTIFIER(:ro_role);
    DROP DATABASE ROLE IF EXISTS IDENTIFIER(:rw_role);
    DROP DATABASE ROLE IF EXISTS IDENTIFIER(:full_role);

    RETURN 'Schema ' || :database_name || '.' || :schema_name || ' was dropped.';
END;
