-- set the environment abbreviation variable
-- -----------------------------------------
SET ENV_ABBR = 'DEV_';
-- -----------------------------------------

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';
SET ENV_WH = $ENV_ABBR || 'PROVISION_WH';
SET ENV_DB = $ENV_ABBR || 'PROVISION_DB';

-- define environment functional roles and associated warehouses
SET ENV_DATA_ENGINEER = $ENV_ABBR || 'DATA_ENGINEER';
SET ENV_DATA_ENGINEER_WH = $ENV_ABBR || 'DATA_ENGINEER_WH';
SET ENV_DATA_ANALYST = $ENV_ABBR || 'DATA_ANALYST';
SET ENV_DATA_ANALYST_WH = $ENV_ABBR || 'DATA_ANALYST_WH';

-- create the DATA_ENGINEER and DATA_ANALYST environment functional roles
USE ROLE IDENTIFIER($ENV_USERADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);

CREATE ROLE IDENTIFIER($ENV_DATA_ENGINEER);
GRANT ROLE IDENTIFIER($ENV_DATA_ENGINEER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IDENTIFIER($ENV_DATA_ANALYST);
GRANT ROLE IDENTIFIER($ENV_DATA_ANALYST) TO ROLE IDENTIFIER($ENV_SYSADMIN);

-- create virtual warehouses for each functional role
USE ROLE IDENTIFIER($ENV_SYSADMIN);
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_DATA_ENGINEER_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_DATA_ENGINEER_WH) TO ROLE IDENTIFIER($ENV_DATA_ENGINEER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_DATA_ANALYST_WH) WITH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_DATA_ANALYST_WH) TO ROLE IDENTIFIER($ENV_DATA_ANALYST);