USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE STORAGE INTEGRATION DEMO_AZURE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '123abc...' -- replace with your Azure tenant ID
  STORAGE_ALLOWED_LOCATIONS = ('azure://<storage_account>.blob.core.windows.net/<container_name>/');

DESCRIBE INTEGRATION DEMO_AZURE_INTEGRATION;
-- complete the integration by opening the consent URL

GRANT USAGE ON INTEGRATION DEMO_AZURE_INTEGRATION TO DEV_DATA_ENGINEER;

USE ROLE DEV_DATA_ENGINEER;
USE DATABASE DEV_DWH_DB;
USE SCHEMA EX;

CREATE OR REPLACE STAGE DEMO_AZURE_STAGE
  STORAGE_INTEGRATION = DEMO_AZURE_INTEGRATION
  URL = 'azure://<storage_account>.blob.core.windows.net/<container_name>/';

LIST @DEMO_AZURE_STAGE;