USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION DEMO_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::999999999999:role/<iam-role-name>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<bucket-name>');

GRANT USAGE ON INTEGRATION DEMO_S3_INTEGRATION TO ROLE DEV_DATA_ENGINEER;

USE ROLE DEV_DATA_ENGINEER;
USE DATABASE DEV_DWH_DB;
USE SCHEMA EX;

CREATE STAGE DEMO_S3_STAGE 
URL = 's3://<bucket-name>'
STORAGE_INTEGRATION = DEMO_S3_INTEGRATION;

LIST @DEMO_S3_STAGE;