CREATE OR REPLACE PROCEDURE ADM.SP_WRITE_PPN_LOG(
  "PPN_ID" NUMBER(38,0),
  "SOURCE_ID" VARCHAR,
  --"SOURCE_NAME" VARCHAR,
  "PPN_PHASE" VARCHAR,
  "LOG_START" TIMESTAMP_NTZ(9),
  "LOG_END" TIMESTAMP_NTZ(9),
  "DURATION_MSEC" NUMBER(38,0),
  "LOG_STATUS" VARCHAR,
  "SOURCE_OBJECT" VARCHAR,
  "TARGET_OBJECT" VARCHAR,
  "ROW_COUNT" NUMBER(38,0),
  "LOG_MESSAGE" VARCHAR,
  "LOG_MESSAGE_DETAIL" VARCHAR,
  "RUN_ID" VARCHAR DEFAULT 'N/A'
)
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
  INSERT INTO ADM.PPN_LOG
  (
    PPN_ID,
    SOURCE_ID,
    --SOURCE_NAME,
    PPN_PHASE,
    LOG_START,
    LOG_END,
    DURATION_MSEC,
    LOG_STATUS,
    SOURCE_OBJECT,
    TARGET_OBJECT,
    RUN_ID,
    ROW_COUNT,
    LOG_MESSAGE,
    LOG_MESSAGE_DETAIL
  )
  VALUES
  (
    :PPN_ID,
    :SOURCE_ID,
    --:SOURCE_NAME,
    :PPN_PHASE,
    :LOG_START,
    :LOG_END,
    :DURATION_MSEC,
    :LOG_STATUS,
    :SOURCE_OBJECT,
    :TARGET_OBJECT,
    :RUN_ID,
    :ROW_COUNT,
    :LOG_MESSAGE,
    :LOG_MESSAGE_DETAIL
  );

  RETURN SQLROWCOUNT;
END;