-- ============================================================================
-- Functional roles + one warehouse per role, per environment
-- Terraform mapping: one module "functional_role" (snowflake_account_role +
--   snowflake_warehouse + 2 grants), for_each over the role list below.
-- Fixes vs. v1: $ENV_REPORTE_FINANCE typo, PROVISION_WH -> PLATFORM_WH.
--
-- Role list (keep in sync with databases/config/*.yaml):
--   TRANSFORMER          (data engineering / dbt)
--   ANALYST
--   DATA_LOADER          (ADF service user)
--   REPORTER             (BI generic)
--   REPORTER_BILLING     (PBI Direct Query SSO)
--   REPORTER_FINANCE     (PBI Direct Query SSO)
--   REPORTER_MARKETING   (PBI Direct Query SSO)
--   IT_GOVERNANCE
-- ============================================================================

-- set the environment abbreviation variable
-- -----------------------------------------
SET ENV_ABBR = 'DEV_';
-- -----------------------------------------

SET ENV_SYSADMIN  = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';
SET ENV_WH        = 'PLATFORM_WH';

SET ENV_TRANSFORMER           = $ENV_ABBR || 'TRANSFORMER';
SET ENV_TRANSFORMER_WH        = $ENV_ABBR || 'TRANSFORMER_WH';
SET ENV_ANALYST               = $ENV_ABBR || 'ANALYST';
SET ENV_ANALYST_WH            = $ENV_ABBR || 'ANALYST_WH';
SET ENV_DATA_LOADER           = $ENV_ABBR || 'DATA_LOADER';
SET ENV_DATA_LOADER_WH        = $ENV_ABBR || 'DATA_LOADER_WH';
SET ENV_REPORTER              = $ENV_ABBR || 'REPORTER';
SET ENV_REPORTER_WH           = $ENV_ABBR || 'REPORTER_WH';
SET ENV_REPORTER_BILLING      = $ENV_ABBR || 'REPORTER_BILLING';
SET ENV_REPORTER_BILLING_WH   = $ENV_ABBR || 'REPORTER_BILLING_WH';
SET ENV_REPORTER_FINANCE      = $ENV_ABBR || 'REPORTER_FINANCE';
SET ENV_REPORTER_FINANCE_WH   = $ENV_ABBR || 'REPORTER_FINANCE_WH';
SET ENV_REPORTER_MARKETING    = $ENV_ABBR || 'REPORTER_MARKETING';
SET ENV_REPORTER_MARKETING_WH = $ENV_ABBR || 'REPORTER_MARKETING_WH';
SET ENV_IT_GOVERNANCE         = $ENV_ABBR || 'IT_GOVERNANCE';
SET ENV_IT_GOVERNANCE_WH      = $ENV_ABBR || 'IT_GOVERNANCE_WH';

-- ----------------------------------------------------------------------------
-- create functional roles, grant to environment sysadmin
-- ----------------------------------------------------------------------------
USE ROLE IDENTIFIER($ENV_USERADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_TRANSFORMER);
GRANT ROLE IDENTIFIER($ENV_TRANSFORMER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_ANALYST);
GRANT ROLE IDENTIFIER($ENV_ANALYST) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_DATA_LOADER);
GRANT ROLE IDENTIFIER($ENV_DATA_LOADER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER);
GRANT ROLE IDENTIFIER($ENV_REPORTER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_BILLING);
GRANT ROLE IDENTIFIER($ENV_REPORTER_BILLING) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_FINANCE);
GRANT ROLE IDENTIFIER($ENV_REPORTER_FINANCE) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_MARKETING);
GRANT ROLE IDENTIFIER($ENV_REPORTER_MARKETING) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_IT_GOVERNANCE);
GRANT ROLE IDENTIFIER($ENV_IT_GOVERNANCE) TO ROLE IDENTIFIER($ENV_SYSADMIN);

-- ----------------------------------------------------------------------------
-- create one warehouse per functional role, grant usage
-- ----------------------------------------------------------------------------
USE ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_TRANSFORMER_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_TRANSFORMER_WH) TO ROLE IDENTIFIER($ENV_TRANSFORMER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_ANALYST_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_ANALYST_WH) TO ROLE IDENTIFIER($ENV_ANALYST);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_DATA_LOADER_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_DATA_LOADER_WH) TO ROLE IDENTIFIER($ENV_DATA_LOADER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_WH) TO ROLE IDENTIFIER($ENV_REPORTER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_BILLING_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_BILLING_WH) TO ROLE IDENTIFIER($ENV_REPORTER_BILLING);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_FINANCE_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_FINANCE_WH) TO ROLE IDENTIFIER($ENV_REPORTER_FINANCE);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_MARKETING_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_MARKETING_WH) TO ROLE IDENTIFIER($ENV_REPORTER_MARKETING);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_IT_GOVERNANCE_WH) WITH
  WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_IT_GOVERNANCE_WH) TO ROLE IDENTIFIER($ENV_IT_GOVERNANCE);
