-- set the environment abbreviation variable
-- -----------------------------------------
SET ENV_ABBR = 'DEV_';
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'ADM';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_ANALYST;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'RAW';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'BRONZE';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'BRONZE_HIST';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'SILVER';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_ANALYST;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'GOLD';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_ANALYST;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------

-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'GOLD_BILLING';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_ANALYST;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER_BILLING;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'GOLD_FINANCE';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_ANALYST;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER_FINANCE;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------
-- define the database name, schema name, and schema access roles
SET DB_NAME = $ENV_ABBR || 'DB';
SET SCHEMA_NAME = 'GOLD_MARKETING';
SET RO_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_RO_AR';
SET FULL_ROLE = $DB_NAME || '.' || $SCHEMA_NAME || '_FULL_AR';

-- define environment administration roles
SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';
SET ENV_WH = 'PLATFORM_WH';
SET ENV_DB = 'PLATFORM_DB';

-- create the schema
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE IDENTIFIER($ENV_WH);
USE DATABASE IDENTIFIER($ENV_DB);
USE SCHEMA RBAC;
CALL CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);

-- grant schema access roles to functional roles
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_ANALYST;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_IT_GOVERNANCE;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE) TO ROLE DEV_REPORTER_MARKETING;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_TRANSFORMER;
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE DEV_DATA_LOADER;
-- -----------------------------------------