USE ROLE SYSADMIN;
USE DATABASE PLATFORM_DB;
CREATE SCHEMA IF NOT EXISTS NETWORK_RULES;

USE ROLE ACCOUNTADMIN;

-- In516ht network
CREATE OR REPLACE NETWORK RULE PLATFORM_DB.NETWORK_RULES.IN516HT_NETWORK
TYPE = IPV4
VALUE_LIST = ('89.212.52.137/32')
MODE = INGRESS
COMMENT = 'In516ht IP ranges';

-- Customer network
CREATE OR REPLACE NETWORK RULE PLATFORM_DB.NETWORK_RULES.TBAYTEL_NETWORK
TYPE = IPV4
VALUE_LIST = ('0.0.0.0/0') -- replace with actual Tbaytel IP ranges before applying a network policy
MODE = INGRESS
COMMENT = 'Tbaytel IP';


USE ROLE SYSADMIN;
USE DATABASE PLATFORM_DB;
CREATE SCHEMA IF NOT EXISTS SHARED_WORKSPACE;