CREATE STAGE  IF NOT EXISTS ADM.EXT_STAGE_AZURE
URL='azure://snowflakeloaderdev.blob.core.windows.net/dev-load/ENDUR_ORA/'
STORAGE_INTEGRATION = DEV_AZURE_BLOB_INTEGRATION
DIRECTORY=(ENABLE=TRUE AUTO_REFRESH=FALSE)
;