-- template for creating a user with SSO authentication
-- the user email must match the Entra ID
/*
USE ROLE USERADMIN;
CREATE USER <username> 
PASSWORD = '' 
LOGIN_NAME = '...@example.com' -- replace with actual user email
DISPLAY_NAME = 'Firstname Lastname' -- replace with actual user details
DEFAULT_ROLE = DEV_DATA_ENGINEER;

USE ROLE DEV_USERADMIN;
GRANT ROLE DEV_DATA_ENGINEER TO USER <username>;
*/
/*
USE ROLE USERADMIN;
CREATE USER BRANKOZ
PASSWORD = '111' 
LOGIN_NAME = 'BRANKOZ' -- replace with actual user email
DISPLAY_NAME = 'BRANKOZ' -- replace with actual user details
DEFAULT_ROLE = ACCOUNTADMIN;

USE ROLE DEV_USERADMIN;
GRANT ROLE ACCOUNTADMIN TO USER BRANKOZ;
*/
-- ============================================================
-- ENVIRONMENT CONFIGURATION
-- ============================================================

SET ENV_ABBR = 'DEV_';

SET ENV_SYSADMIN  = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';


-- ============================================================
-- USER AND ROLE NAMES
-- ============================================================

SET USER_ACCOUNTADMIN       = 'BLEND_ACCOUNTADMIN';
SET USER_TRANSFORMER        = 'BLEND_TRANSFORMER';
SET USER_ANALYST            = 'BLEND_ANALYST';
SET USER_DATA_LOADER        = 'BLEND_DATA_LOADER';
SET USER_REPORTER           = 'BLEND_REPORTER';
SET USER_REPORTER_BILLING   = 'BLEND_REPORTER_BILLING';
SET USER_REPORTER_FINANCE   = 'BLEND_REPORTER_FINANCE';
SET USER_REPORTER_MARKETING = 'BLEND_REPORTER_MARKETING';
SET USER_IT_GOVERNANCE      = 'BLEND_IT_GOVERNANCE';

SET ROLE_TRANSFORMER        = $ENV_ABBR || 'TRANSFORMER';
SET ROLE_ANALYST            = $ENV_ABBR || 'ANALYST';
SET ROLE_DATA_LOADER        = $ENV_ABBR || 'DATA_LOADER';
SET ROLE_REPORTER           = $ENV_ABBR || 'REPORTER';
SET ROLE_REPORTER_BILLING   = $ENV_ABBR || 'REPORTER_BILLING';
SET ROLE_REPORTER_FINANCE   = $ENV_ABBR || 'REPORTER_FINANCE';
SET ROLE_REPORTER_MARKETING = $ENV_ABBR || 'REPORTER_MARKETING';
SET ROLE_IT_GOVERNANCE      = $ENV_ABBR || 'IT_GOVERNANCE';


-- ============================================================
-- CREATE USERS
-- ============================================================

USE ROLE USERADMIN;


-- ACCOUNTADMIN

CREATE USER IDENTIFIER($USER_ACCOUNTADMIN)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_ACCOUNTADMIN
    DISPLAY_NAME = $USER_ACCOUNTADMIN
    DEFAULT_ROLE = 'ACCOUNTADMIN'
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- TRANSFORMER

CREATE USER IDENTIFIER($USER_TRANSFORMER)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_TRANSFORMER
    DISPLAY_NAME = $USER_TRANSFORMER
    DEFAULT_ROLE = $ROLE_TRANSFORMER
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- ANALYST

CREATE USER IDENTIFIER($USER_ANALYST)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_ANALYST
    DISPLAY_NAME = $USER_ANALYST
    DEFAULT_ROLE = $ROLE_ANALYST
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- DATA_LOADER

CREATE USER IDENTIFIER($USER_DATA_LOADER)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_DATA_LOADER
    DISPLAY_NAME = $USER_DATA_LOADER
    DEFAULT_ROLE = $ROLE_DATA_LOADER
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- REPORTER

CREATE USER IDENTIFIER($USER_REPORTER)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_REPORTER
    DISPLAY_NAME = $USER_REPORTER
    DEFAULT_ROLE = $ROLE_REPORTER
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- REPORTER_BILLING

CREATE USER IDENTIFIER($USER_REPORTER_BILLING)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_REPORTER_BILLING
    DISPLAY_NAME = $USER_REPORTER_BILLING
    DEFAULT_ROLE = $ROLE_REPORTER_BILLING
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- REPORTER_FINANCE

CREATE USER IDENTIFIER($USER_REPORTER_FINANCE)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_REPORTER_FINANCE
    DISPLAY_NAME = $USER_REPORTER_FINANCE
    DEFAULT_ROLE = $ROLE_REPORTER_FINANCE
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- REPORTER_MARKETING

CREATE USER IDENTIFIER($USER_REPORTER_MARKETING)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_REPORTER_MARKETING
    DISPLAY_NAME = $USER_REPORTER_MARKETING
    DEFAULT_ROLE = $ROLE_REPORTER_MARKETING
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- IT_GOVERNANCE

CREATE USER IDENTIFIER($USER_IT_GOVERNANCE)
    PASSWORD     = '1111'
    LOGIN_NAME   = $USER_IT_GOVERNANCE
    DISPLAY_NAME = $USER_IT_GOVERNANCE
    DEFAULT_ROLE = $ROLE_IT_GOVERNANCE
    -- MUST_CHANGE_PASSWORD = TRUE
;


-- ============================================================
-- GRANT ENVIRONMENT-SPECIFIC ROLES
-- ============================================================

USE ROLE IDENTIFIER($ENV_USERADMIN);

GRANT ROLE IDENTIFIER($ROLE_TRANSFORMER)
    TO USER IDENTIFIER($USER_TRANSFORMER);

GRANT ROLE IDENTIFIER($ROLE_ANALYST)
    TO USER IDENTIFIER($USER_ANALYST);

GRANT ROLE IDENTIFIER($ROLE_DATA_LOADER)
    TO USER IDENTIFIER($USER_DATA_LOADER);

GRANT ROLE IDENTIFIER($ROLE_REPORTER)
    TO USER IDENTIFIER($USER_REPORTER);

GRANT ROLE IDENTIFIER($ROLE_REPORTER_BILLING)
    TO USER IDENTIFIER($USER_REPORTER_BILLING);

GRANT ROLE IDENTIFIER($ROLE_REPORTER_FINANCE)
    TO USER IDENTIFIER($USER_REPORTER_FINANCE);

GRANT ROLE IDENTIFIER($ROLE_REPORTER_MARKETING)
    TO USER IDENTIFIER($USER_REPORTER_MARKETING);

GRANT ROLE IDENTIFIER($ROLE_IT_GOVERNANCE)
    TO USER IDENTIFIER($USER_IT_GOVERNANCE);


-- ============================================================
-- GRANT ACCOUNTADMIN
-- ACCOUNTADMIN is not environment-specific.
-- ============================================================

USE ROLE SECURITYADMIN;

GRANT ROLE ACCOUNTADMIN
    TO USER IDENTIFIER($USER_ACCOUNTADMIN);