-- create the Matillion service user in the DEV environment
USE ROLE USERADMIN;
CREATE USER SVC_DEV_ADF 
LOGIN_NAME = 'SVC_DEV_ADF' 
DISPLAY_NAME = 'Azure Data Factory'
TYPE = 'SERVICE'
COMMENT = 'ADF DEV service user'
DEFAULT_ROLE = DEV_DATA_LOADER
DEFAULT_WAREHOUSE = DEV_DATA_LOADER_WH;

USE ROLE DEV_USERADMIN;
GRANT ROLE DEV_DATA_LOADER TO USER SVC_DEV_ADF;

ALTER USER SVC_DEV_MATILLION SET RSA_PUBLIC_KEY = 'MII...'; -- Replace with actual RSA public key