-- ============================================================
-- ENVIRONMENT FUNCTIONAL ROLES + VIRTUAL WAREHOUSES
-- RUN PER ENVIRONMENT.  Set ENV_ABBR, then run the whole file.
--
-- Functional roles (one dedicated warehouse each, for per-workload
-- cost attribution):
--   TRANSFORMER         data engineering / transformation
--   ANALYST             interactive analysis and development
--   DATA_LOADER         ingestion role used by Azure Data Factory
--   REPORTER            general BI / reporting
--   REPORTER_BILLING    billing reporting (Power BI DirectQuery SSO)
--   REPORTER_FINANCE    finance reporting (Power BI DirectQuery SSO)
--   REPORTER_MARKETING  marketing reporting (Power BI DirectQuery SSO)
--   IT_GOVERNANCE       governance / monitoring / admin reporting
--   DEPLOYER            CI/CD deployment (schemachange/dbt) - applies
--                       DDL to the env schemas; reads the git repos in
--                       PLATFORM_DB.DEPLOYMENT. Distinct from TRANSFORMER
--                       (interactive) and TERRAFORM_ADMIN (account-level).
-- ============================================================
SET ENV_ABBR = 'DEV_';

SET ENV_SYSADMIN  = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';

SET ENV_TRANSFORMER        = $ENV_ABBR || 'TRANSFORMER';
SET ENV_TRANSFORMER_WH     = $ENV_ABBR || 'TRANSFORMER_WH';
SET ENV_ANALYST            = $ENV_ABBR || 'ANALYST';
SET ENV_ANALYST_WH         = $ENV_ABBR || 'ANALYST_WH';
SET ENV_DATA_LOADER        = $ENV_ABBR || 'DATA_LOADER';
SET ENV_DATA_LOADER_WH     = $ENV_ABBR || 'DATA_LOADER_WH';
SET ENV_REPORTER           = $ENV_ABBR || 'REPORTER';
SET ENV_REPORTER_WH        = $ENV_ABBR || 'REPORTER_WH';
SET ENV_REPORTER_BILLING   = $ENV_ABBR || 'REPORTER_BILLING';
SET ENV_REPORTER_BILLING_WH = $ENV_ABBR || 'REPORTER_BILLING_WH';
SET ENV_REPORTER_FINANCE   = $ENV_ABBR || 'REPORTER_FINANCE';
SET ENV_REPORTER_FINANCE_WH = $ENV_ABBR || 'REPORTER_FINANCE_WH';
SET ENV_REPORTER_MARKETING = $ENV_ABBR || 'REPORTER_MARKETING';
SET ENV_REPORTER_MARKETING_WH = $ENV_ABBR || 'REPORTER_MARKETING_WH';
SET ENV_IT_GOVERNANCE      = $ENV_ABBR || 'IT_GOVERNANCE';
SET ENV_IT_GOVERNANCE_WH   = $ENV_ABBR || 'IT_GOVERNANCE_WH';
SET ENV_DEPLOYER           = $ENV_ABBR || 'DEPLOYER';
SET ENV_DEPLOYER_WH        = $ENV_ABBR || 'DEPLOYER_WH';


-- ============================================================
-- CREATE FUNCTIONAL ROLES
-- ENV_USERADMIN creates them and slots each below ENV_SYSADMIN.
-- ============================================================
USE ROLE IDENTIFIER($ENV_USERADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_TRANSFORMER);
GRANT ROLE IDENTIFIER($ENV_TRANSFORMER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_ANALYST);
GRANT ROLE IDENTIFIER($ENV_ANALYST) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_DATA_LOADER);
GRANT ROLE IDENTIFIER($ENV_DATA_LOADER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER);
GRANT ROLE IDENTIFIER($ENV_REPORTER) TO ROLE IDENTIFIER($ENV_SYSADMIN);

-- NOTE on hierarchy: the three domain reporters are granted to
-- ENV_SYSADMIN for management only (matching the original design).
-- They are NOT granted to the general REPORTER, and REPORTER is NOT
-- granted to them. See README "Reporter model" for the rationale.
CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_BILLING);
GRANT ROLE IDENTIFIER($ENV_REPORTER_BILLING) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_FINANCE);
GRANT ROLE IDENTIFIER($ENV_REPORTER_FINANCE) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_MARKETING);
GRANT ROLE IDENTIFIER($ENV_REPORTER_MARKETING) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_IT_GOVERNANCE);
GRANT ROLE IDENTIFIER($ENV_IT_GOVERNANCE) TO ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE ROLE IF NOT EXISTS IDENTIFIER($ENV_DEPLOYER);
GRANT ROLE IDENTIFIER($ENV_DEPLOYER) TO ROLE IDENTIFIER($ENV_SYSADMIN);


-- ============================================================
-- CREATE WAREHOUSES  (ENV_SYSADMIN owns them; each functional
-- role gets USAGE only on its own warehouse).
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_TRANSFORMER_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_TRANSFORMER_WH) TO ROLE IDENTIFIER($ENV_TRANSFORMER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_ANALYST_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_ANALYST_WH) TO ROLE IDENTIFIER($ENV_ANALYST);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_DATA_LOADER_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_DATA_LOADER_WH) TO ROLE IDENTIFIER($ENV_DATA_LOADER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_WH) TO ROLE IDENTIFIER($ENV_REPORTER);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_BILLING_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_BILLING_WH) TO ROLE IDENTIFIER($ENV_REPORTER_BILLING);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_FINANCE_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_FINANCE_WH) TO ROLE IDENTIFIER($ENV_REPORTER_FINANCE);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_REPORTER_MARKETING_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_REPORTER_MARKETING_WH) TO ROLE IDENTIFIER($ENV_REPORTER_MARKETING);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_IT_GOVERNANCE_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_IT_GOVERNANCE_WH) TO ROLE IDENTIFIER($ENV_IT_GOVERNANCE);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ENV_DEPLOYER_WH)
    WAREHOUSE_TYPE = STANDARD WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($ENV_DEPLOYER_WH) TO ROLE IDENTIFIER($ENV_DEPLOYER);


-- ============================================================
-- DEPLOYER - read access to the CI/CD git repositories.
-- The git repos live in PLATFORM_DB.DEPLOYMENT (account-wide, created
-- in account/13-14). SYSADMIN owns that schema, so it grants the read.
-- Schema-level FULL access on the env schemas is granted in step 04.
-- (Verify the ALL/FUTURE GIT REPOSITORIES grant grammar against
-- current Snowflake docs; grant per-repo if the bulk form is rejected.)
-- ============================================================
USE ROLE SYSADMIN;
GRANT USAGE ON DATABASE PLATFORM_DB              TO ROLE IDENTIFIER($ENV_DEPLOYER);
GRANT USAGE ON SCHEMA   PLATFORM_DB.DEPLOYMENT   TO ROLE IDENTIFIER($ENV_DEPLOYER);
GRANT USAGE ON ALL    GIT REPOSITORIES IN SCHEMA PLATFORM_DB.DEPLOYMENT TO ROLE IDENTIFIER($ENV_DEPLOYER);
GRANT USAGE ON FUTURE GIT REPOSITORIES IN SCHEMA PLATFORM_DB.DEPLOYMENT TO ROLE IDENTIFIER($ENV_DEPLOYER);
