-- ============================================================
-- ENVIRONMENT FUNCTIONAL ROLES + VIRTUAL WAREHOUSES
-- RUN PER ENVIRONMENT.  Set ENV_ABBR, then run the whole file.
--
-- These roles hold the PRIVILEGES and stay owned by {ENV}_USERADMIN.
-- Entra groups are synced in by SCIM as separate roles that hold no
-- privileges; each is granted the matching role here, once, in
-- account/17. Entra manages membership, Snowflake manages access.
--
-- HUMAN roles (an Entra group is granted each one):
--   TRANSFORMER         data engineering / transformation
--   ANALYST             interactive analysis and development
--   REPORTER            reporting on the shared GOLD schema
--   IT_GOVERNANCE       governance / monitoring / admin reporting
--   REPORTER_{domain}   reporting on one GOLD_{domain} mart (13)
--
-- SERVICE roles (no Entra group - used by SVC_ users in 05):
--   DATA_LOADER         Azure Data Factory ingestion
--   DEPLOYER            CI/CD deployment (schemachange/dbt)
--   POWERBI             Power BI service account, reads GOLD + all marts
--
-- Each role gets its own warehouse for per-workload cost attribution.
-- Warehouses are created suspended and cost nothing until used.
-- ============================================================
SET ENV_ABBR = 'DEV_';

SET ENV_SYSADMIN  = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';

-- ---- human roles -------------------------------------------
SET R_TRANSFORMER    = $ENV_ABBR || 'TRANSFORMER';
SET W_TRANSFORMER    = $ENV_ABBR || 'TRANSFORMER_WH';
SET R_ANALYST        = $ENV_ABBR || 'ANALYST';
SET W_ANALYST        = $ENV_ABBR || 'ANALYST_WH';
SET R_REPORTER       = $ENV_ABBR || 'REPORTER';
SET W_REPORTER       = $ENV_ABBR || 'REPORTER_WH';
SET R_IT_GOVERNANCE  = $ENV_ABBR || 'IT_GOVERNANCE';
SET W_IT_GOVERNANCE  = $ENV_ABBR || 'IT_GOVERNANCE_WH';

-- ---- domain reporters (T2 of the Data Domain Map) -----------
SET R_RPT_SMC_MARKETING_COMMS = $ENV_ABBR || 'REPORTER_SMC_MARKETING_COMMS';
SET W_RPT_SMC_MARKETING_COMMS = $ENV_ABBR || 'REPORTER_SMC_MARKETING_COMMS_WH';
SET R_RPT_SMC_SALES           = $ENV_ABBR || 'REPORTER_SMC_SALES';
SET W_RPT_SMC_SALES           = $ENV_ABBR || 'REPORTER_SMC_SALES_WH';
SET R_RPT_FIN_ACCOUNTING      = $ENV_ABBR || 'REPORTER_FIN_ACCOUNTING';
SET W_RPT_FIN_ACCOUNTING      = $ENV_ABBR || 'REPORTER_FIN_ACCOUNTING_WH';
SET R_RPT_FIN_FPNA            = $ENV_ABBR || 'REPORTER_FIN_FPNA';
SET W_RPT_FIN_FPNA            = $ENV_ABBR || 'REPORTER_FIN_FPNA_WH';
SET R_RPT_FIN_PROCUREMENT     = $ENV_ABBR || 'REPORTER_FIN_PROCUREMENT';
SET W_RPT_FIN_PROCUREMENT     = $ENV_ABBR || 'REPORTER_FIN_PROCUREMENT_WH';
SET R_RPT_OPE_CUSTOMER_CARE   = $ENV_ABBR || 'REPORTER_OPE_CUSTOMER_CARE';
SET W_RPT_OPE_CUSTOMER_CARE   = $ENV_ABBR || 'REPORTER_OPE_CUSTOMER_CARE_WH';
SET R_RPT_OPE_FIELD_OPERATIONS = $ENV_ABBR || 'REPORTER_OPE_FIELD_OPERATIONS';
SET W_RPT_OPE_FIELD_OPERATIONS = $ENV_ABBR || 'REPORTER_OPE_FIELD_OPERATIONS_WH';
SET R_RPT_HR_PAYROLL          = $ENV_ABBR || 'REPORTER_HR_PAYROLL_PEOPLE_TALENT';
SET W_RPT_HR_PAYROLL          = $ENV_ABBR || 'REPORTER_HR_PAYROLL_PEOPLE_TALENT_WH';
SET R_RPT_HR_HEALTH_SAFETY    = $ENV_ABBR || 'REPORTER_HR_HEALTH_SAFETY';
SET W_RPT_HR_HEALTH_SAFETY    = $ENV_ABBR || 'REPORTER_HR_HEALTH_SAFETY_WH';
SET R_RPT_HR_OCCUPATIONAL_HEALTH = $ENV_ABBR || 'REPORTER_HR_OCCUPATIONAL_HEALTH';
SET W_RPT_HR_OCCUPATIONAL_HEALTH = $ENV_ABBR || 'REPORTER_HR_OCCUPATIONAL_HEALTH_WH';
SET R_RPT_NET_IT_SECURITY     = $ENV_ABBR || 'REPORTER_NET_IT_SECURITY';
SET W_RPT_NET_IT_SECURITY     = $ENV_ABBR || 'REPORTER_NET_IT_SECURITY_WH';
SET R_RPT_NET_NETWORK_OPS     = $ENV_ABBR || 'REPORTER_NET_NETWORK_OPERATIONS';
SET W_RPT_NET_NETWORK_OPS     = $ENV_ABBR || 'REPORTER_NET_NETWORK_OPERATIONS_WH';
SET R_RPT_NET_ENGINEERING     = $ENV_ABBR || 'REPORTER_NET_ENGINEERING';
SET W_RPT_NET_ENGINEERING     = $ENV_ABBR || 'REPORTER_NET_ENGINEERING_WH';

-- ---- service roles -----------------------------------------
SET R_DATA_LOADER = $ENV_ABBR || 'DATA_LOADER';
SET W_DATA_LOADER = $ENV_ABBR || 'DATA_LOADER_WH';
SET R_DEPLOYER    = $ENV_ABBR || 'DEPLOYER';
SET W_DEPLOYER    = $ENV_ABBR || 'DEPLOYER_WH';
SET R_POWERBI     = $ENV_ABBR || 'POWERBI';
SET W_POWERBI     = $ENV_ABBR || 'POWERBI_WH';


-- ============================================================
-- CREATE ROLES
-- ENV_USERADMIN creates them; each is granted to ENV_SYSADMIN so the
-- environment admin can assume and manage it.
--
-- NOTE: {ENV}_POWERBI was previously called {ENV}_REPORTER. It was
-- renamed because {ENV}_REPORTER is now the HUMAN role for the shared
-- GOLD schema. The service account keeps the broad GOLD + all-marts
-- read; the human role does not.
-- ============================================================
USE ROLE IDENTIFIER($ENV_USERADMIN);

-- human
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_TRANSFORMER);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_ANALYST);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_REPORTER);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_IT_GOVERNANCE);

-- domain reporters
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_SMC_MARKETING_COMMS);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_SMC_SALES);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_FIN_ACCOUNTING);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_FIN_FPNA);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_FIN_PROCUREMENT);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_HR_PAYROLL);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_HR_HEALTH_SAFETY);
-- Occupational health is special-category (medical) personal data.
-- The role is created so the Entra mapping is complete, but do NOT
-- grant it access to any schema until the handling of this data is
-- agreed with Tbaytel's privacy function.
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_NET_IT_SECURITY);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_NET_NETWORK_OPS);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_NET_ENGINEERING);

-- service
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_DATA_LOADER);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_DEPLOYER);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_POWERBI);

-- management hierarchy
GRANT ROLE IDENTIFIER($R_TRANSFORMER)    TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_ANALYST)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_REPORTER)       TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_IT_GOVERNANCE)  TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_SMC_MARKETING_COMMS)    TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_SMC_SALES)              TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_FIN_ACCOUNTING)         TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_FIN_FPNA)               TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_FIN_PROCUREMENT)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE)      TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS)   TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_HR_PAYROLL)             TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_HR_HEALTH_SAFETY)       TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH) TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_NET_IT_SECURITY)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_NET_NETWORK_OPS)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_NET_ENGINEERING)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_DATA_LOADER)    TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_DEPLOYER)       TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_POWERBI)        TO ROLE IDENTIFIER($ENV_SYSADMIN);


-- ============================================================
-- CREATE WAREHOUSES
-- One per role. ENV_SYSADMIN owns them; each role gets USAGE on its
-- own warehouse only. All X-Small and initially suspended.
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_TRANSFORMER)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_ANALYST)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_REPORTER)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_IT_GOVERNANCE)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_SMC_MARKETING_COMMS)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_SMC_SALES)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_FIN_ACCOUNTING)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_FIN_FPNA)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_FIN_PROCUREMENT)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_OPE_CUSTOMER_CARE)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_OPE_FIELD_OPERATIONS)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_HR_PAYROLL)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_HR_HEALTH_SAFETY)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_HR_OCCUPATIONAL_HEALTH)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_NET_IT_SECURITY)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_NET_NETWORK_OPS)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_NET_ENGINEERING)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_DATA_LOADER)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_DEPLOYER)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_POWERBI)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($W_TRANSFORMER)   TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_ANALYST)       TO ROLE IDENTIFIER($R_ANALYST);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_REPORTER)      TO ROLE IDENTIFIER($R_REPORTER);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_IT_GOVERNANCE) TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_SMC_MARKETING_COMMS)    TO ROLE IDENTIFIER($R_RPT_SMC_MARKETING_COMMS);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_SMC_SALES)              TO ROLE IDENTIFIER($R_RPT_SMC_SALES);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_FIN_ACCOUNTING)         TO ROLE IDENTIFIER($R_RPT_FIN_ACCOUNTING);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_FIN_FPNA)               TO ROLE IDENTIFIER($R_RPT_FIN_FPNA);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_FIN_PROCUREMENT)        TO ROLE IDENTIFIER($R_RPT_FIN_PROCUREMENT);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_OPE_CUSTOMER_CARE)      TO ROLE IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_OPE_FIELD_OPERATIONS)   TO ROLE IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_HR_PAYROLL)             TO ROLE IDENTIFIER($R_RPT_HR_PAYROLL);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_HR_HEALTH_SAFETY)       TO ROLE IDENTIFIER($R_RPT_HR_HEALTH_SAFETY);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_HR_OCCUPATIONAL_HEALTH) TO ROLE IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_NET_IT_SECURITY)        TO ROLE IDENTIFIER($R_RPT_NET_IT_SECURITY);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_NET_NETWORK_OPS)        TO ROLE IDENTIFIER($R_RPT_NET_NETWORK_OPS);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_NET_ENGINEERING)        TO ROLE IDENTIFIER($R_RPT_NET_ENGINEERING);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_DATA_LOADER)   TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_DEPLOYER)      TO ROLE IDENTIFIER($R_DEPLOYER);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_POWERBI)       TO ROLE IDENTIFIER($R_POWERBI);


-- ============================================================
-- DEPLOYER - read access to the CI/CD git repositories in
-- PLATFORM_DB.DEPLOYMENT (created in account/13-14). SYSADMIN owns
-- that schema, so it grants the read. Schema-level access on the
-- environment schemas is granted in 04.
-- ============================================================
USE ROLE SYSADMIN;
GRANT USAGE ON DATABASE PLATFORM_DB            TO ROLE IDENTIFIER($R_DEPLOYER);
GRANT USAGE ON SCHEMA   PLATFORM_DB.DEPLOYMENT TO ROLE IDENTIFIER($R_DEPLOYER);

-- Run AFTER the git repositories exist (account/13-14). The per-repo
-- form is always valid; the ALL/FUTURE bulk form is not confirmed for
-- GIT REPOSITORIES - use per-repo if it is rejected.
-- GRANT USAGE ON GIT REPOSITORY PLATFORM_DB.DEPLOYMENT.BB_TBAYTEL_REPO TO ROLE IDENTIFIER($R_DEPLOYER);


-- ============================================================
-- VALIDATION
-- ============================================================
-- Expect 20 roles and 20 warehouses for this environment.
SHOW ROLES LIKE $ENV_ABBR || '%';
SHOW WAREHOUSES LIKE $ENV_ABBR || '%';
