-- ============================================================
-- ENVIRONMENT SCHEMAS  ({ENV}_DB.*)  + access-role grants
-- RUN PER ENVIRONMENT.  Set ENV_ABBR, then run the whole file.
--
-- For each schema this:
--   1. calls CREATE_SCHEMA (creates schema + RO/RW/FULL database
--      roles + all/future object grants),
--   2. sets a Time Travel retention tier,
--   3. grants the RO / FULL access roles to functional roles.
--
-- Runs as ENV_SYSADMIN (owns {ENV}_DB and the access roles).
-- Requires 01 (platform grants) + 03 ({ENV}_DB) to have run.
--
-- NOTE: IDENTIFIER() accepts a single variable/literal, not an
-- inline expression. Qualified names are built into SET variables
-- first (SCHEMA_FQN, RO_ROLE, FULL_ROLE), then passed to IDENTIFIER.
--
-- Medallion layout (Standards 4.1):
--   ADM, RAW, BRONZE, BRONZE_HIST, SILVER, GOLD
--   + 13 GOLD_{domain} marts, one per T2 domain of the client's
--     Data Domain Map. 19 schemas in total.
--
-- Retention tiers (DATA_RETENTION_TIME_IN_DAYS).
-- Principle: Time Travel buys ACCIDENT recovery, not history, and is
-- billed on churn x days. Retention is therefore set by how hard the
-- content is to REBUILD, not by how important it is.
--   RAW / BRONZE          1    re-loadable from the source extract
--   SILVER / GOLD*        7    rebuildable from the layer above
--                              (SILVER from BRONZE_HIST, GOLD from
--                              SILVER); high churn on every load
--   BRONZE_HIST / ADM     30   NOT rebuildable - the replay source and
--                              the run-state / audit log. Losing either
--                              breaks rerun and lineage.
-- Business Critical allows up to 90 days if policy later requires more.
-- ============================================================
SET ENV_ABBR = 'DEV_';
SET DB_NAME  = $ENV_ABBR || 'DB';

SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';

-- functional role names (env-prefixed)
SET R_TRANSFORMER   = $ENV_ABBR || 'TRANSFORMER';
SET R_ANALYST       = $ENV_ABBR || 'ANALYST';
SET R_DATA_LOADER   = $ENV_ABBR || 'DATA_LOADER';
SET R_REPORTER      = $ENV_ABBR || 'REPORTER';      -- human, shared GOLD
SET R_POWERBI       = $ENV_ABBR || 'POWERBI';       -- service, GOLD + all marts
SET R_IT_GOVERNANCE = $ENV_ABBR || 'IT_GOVERNANCE';
SET R_DEPLOYER      = $ENV_ABBR || 'DEPLOYER';
-- domain reporter roles (created in 02) - one per GOLD_{domain} mart
SET R_RPT_SMC_MARKETING_COMMS    = $ENV_ABBR || 'REPORTER_SMC_MARKETING_COMMS';
SET R_RPT_SMC_SALES              = $ENV_ABBR || 'REPORTER_SMC_SALES';
SET R_RPT_FIN_ACCOUNTING         = $ENV_ABBR || 'REPORTER_FIN_ACCOUNTING';
SET R_RPT_FIN_FPNA               = $ENV_ABBR || 'REPORTER_FIN_FPNA';
SET R_RPT_FIN_PROCUREMENT        = $ENV_ABBR || 'REPORTER_FIN_PROCUREMENT';
SET R_RPT_OPE_CUSTOMER_CARE      = $ENV_ABBR || 'REPORTER_OPE_CUSTOMER_CARE';
SET R_RPT_OPE_FIELD_OPERATIONS   = $ENV_ABBR || 'REPORTER_OPE_FIELD_OPERATIONS';
SET R_RPT_HR_PAYROLL             = $ENV_ABBR || 'REPORTER_HR_PAYROLL_PEOPLE_TALENT';
SET R_RPT_HR_HEALTH_SAFETY       = $ENV_ABBR || 'REPORTER_HR_HEALTH_SAFETY';
SET R_RPT_HR_OCCUPATIONAL_HEALTH = $ENV_ABBR || 'REPORTER_HR_OCCUPATIONAL_HEALTH';
SET R_RPT_NET_IT_SECURITY        = $ENV_ABBR || 'REPORTER_NET_IT_SECURITY';
SET R_RPT_NET_NETWORK_OPS        = $ENV_ABBR || 'REPORTER_NET_NETWORK_OPERATIONS';
SET R_RPT_NET_ENGINEERING        = $ENV_ABBR || 'REPORTER_NET_ENGINEERING';

-- context for the CREATE_SCHEMA procedure (set once)
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE PLATFORM_WH;
USE DATABASE PLATFORM_DB;
USE SCHEMA RBAC;


-- ------------------------------------------------------------
-- ADM
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'ADM';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
-- 30: run state + audit log. Not rebuildable; loss breaks rerun logic.
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 30;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- RAW
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'RAW';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 1;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- BRONZE
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'BRONZE';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 1;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- BRONZE_HIST
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'BRONZE_HIST';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
-- 30: the replay / lineage source. No upstream to rebuild it from.
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 30;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- SILVER
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'SILVER';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD  (shared, business-facing)
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
-- 7: rebuildable from SILVER; full-refresh churn makes longer costly.
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ============================================================
-- GOLD_{domain} MARTS  -  one per T2 domain of the Data Domain Map.
--
-- Each mart gets RO for: ANALYST, IT_GOVERNANCE, the POWERBI service
-- role, and its OWN domain reporter. {ENV}_REPORTER is deliberately
-- absent - it reads the shared GOLD schema only. Conformed dimensions
-- reach a mart as views over GOLD (ownership chain), not as access to
-- GOLD itself; the Gold table and the view must be created by the same
-- role for that to work - use {ENV}_DEPLOYER for both.
--
-- Retention 7 days, as for GOLD: rebuildable from SILVER, high churn.
-- ============================================================

-- ------------------------------------------------------------
-- GOLD_SMC_MARKETING_COMMS
-- Sales, Marketing & Comms  >  Marketing & Comms
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_SMC_MARKETING_COMMS';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_SMC_MARKETING_COMMS);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_SMC_SALES
-- Sales, Marketing & Comms  >  Sales
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_SMC_SALES';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_SMC_SALES);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_FIN_ACCOUNTING
-- Finance  >  Accounting
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_FIN_ACCOUNTING';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_FIN_ACCOUNTING);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_FIN_FPNA
-- Finance  >  FP&A
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_FIN_FPNA';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_FIN_FPNA);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_FIN_PROCUREMENT
-- Finance  >  Procurement
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_FIN_PROCUREMENT';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_FIN_PROCUREMENT);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_OPE_CUSTOMER_CARE
-- Operations & OPE  >  Customer Care
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_OPE_CUSTOMER_CARE';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_OPE_FIELD_OPERATIONS
-- Operations & OPE  >  Field Operations
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_OPE_FIELD_OPERATIONS';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_HR_PAYROLL_PEOPLE_TALENT
-- Human Resources  >  Payroll, People & Talent
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_HR_PAYROLL_PEOPLE_TALENT';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_HR_PAYROLL);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_HR_HEALTH_SAFETY
-- Human Resources  >  Health & Safety
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_HR_HEALTH_SAFETY';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_HR_HEALTH_SAFETY);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_HR_OCCUPATIONAL_HEALTH
-- Human Resources  >  Occupational Health
-- ------------------------------------------------------------
-- Occupational health is special-category (medical) personal data.
-- The schema exists for completeness, but confirm handling with
-- Tbaytel's privacy function before any data is loaded into it.
SET SCHEMA_NAME = 'GOLD_HR_OCCUPATIONAL_HEALTH';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_NET_IT_SECURITY
-- Networks & Technology  >  IT & Security
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_NET_IT_SECURITY';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_NET_IT_SECURITY);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_NET_NETWORK_OPERATIONS
-- Networks & Technology  >  Network Operations
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_NET_NETWORK_OPERATIONS';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_NET_NETWORK_OPS);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ------------------------------------------------------------
-- GOLD_NET_ENGINEERING
-- Networks & Technology  >  Engineering
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_NET_ENGINEERING';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_POWERBI);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_RPT_NET_ENGINEERING);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DEPLOYER);


-- ============================================================
-- VALIDATION
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);
-- Expect 19 schemas: ADM, RAW, BRONZE, BRONZE_HIST, SILVER, GOLD
-- + 13 GOLD_{domain} marts. No PUBLIC.
SHOW SCHEMAS IN DATABASE IDENTIFIER($DB_NAME);
