-- ============================================================
-- ENVIRONMENT SCHEMAS  ({ENV}_DB.*)  + access-role grants
-- RUN PER ENVIRONMENT.  Set ENV_ABBR, then run the whole file.
--
-- For each schema this:
--   1. calls CREATE_SCHEMA (creates schema + RO/RW/FULL database
--      roles + all/future object grants),
--   2. sets a Time Travel retention tier,
--   3. grants the RO / FULL access roles to functional roles.
--
-- Runs as ENV_SYSADMIN (owns {ENV}_DB and the access roles).
-- Requires 01 (platform grants) + 03 ({ENV}_DB) to have run.
--
-- NOTE: IDENTIFIER() accepts a single variable/literal, not an
-- inline expression. Qualified names are built into SET variables
-- first (SCHEMA_FQN, RO_ROLE, FULL_ROLE), then passed to IDENTIFIER.
--
-- Medallion layout (Standards 4.1):
--   ADM, RAW, BRONZE, BRONZE_HIST, SILVER,
--   GOLD, GOLD_BILLING, GOLD_FINANCE, GOLD_MARKETING
--
-- Retention tiers (DATA_RETENTION_TIME_IN_DAYS) - adjust to policy:
--   RAW / BRONZE                 1   (re-loadable landing/raw)
--   ADM / BRONZE_HIST / SILVER   7
--   GOLD*                        14  (curated, business-facing)
-- ============================================================
SET ENV_ABBR = 'DEV_';
SET DB_NAME  = $ENV_ABBR || 'DB';

SET ENV_SYSADMIN = $ENV_ABBR || 'SYSADMIN';

-- functional role names (env-prefixed)
SET R_TRANSFORMER        = $ENV_ABBR || 'TRANSFORMER';
SET R_ANALYST            = $ENV_ABBR || 'ANALYST';
SET R_DATA_LOADER        = $ENV_ABBR || 'DATA_LOADER';
SET R_REPORTER           = $ENV_ABBR || 'REPORTER';
SET R_REPORTER_BILLING   = $ENV_ABBR || 'REPORTER_BILLING';
SET R_REPORTER_FINANCE   = $ENV_ABBR || 'REPORTER_FINANCE';
SET R_REPORTER_MARKETING = $ENV_ABBR || 'REPORTER_MARKETING';
SET R_IT_GOVERNANCE      = $ENV_ABBR || 'IT_GOVERNANCE';

-- context for the CREATE_SCHEMA procedure (set once)
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE PLATFORM_WH;
USE DATABASE PLATFORM_DB;
USE SCHEMA RBAC;


-- ------------------------------------------------------------
-- ADM
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'ADM';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- RAW
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'RAW';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 1;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- BRONZE
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'BRONZE';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 1;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- BRONZE_HIST
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'BRONZE_HIST';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- SILVER
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'SILVER';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 7;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- GOLD  (shared, business-facing)
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 14;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- GOLD_BILLING
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_BILLING';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 14;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER_BILLING);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- GOLD_FINANCE
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_FINANCE';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 14;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER_FINANCE);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ------------------------------------------------------------
-- GOLD_MARKETING
-- ------------------------------------------------------------
SET SCHEMA_NAME = 'GOLD_MARKETING';
SET SCHEMA_FQN  = $DB_NAME || '.' || $SCHEMA_NAME;
SET RO_ROLE     = $SCHEMA_FQN || '_RO_AR';
SET FULL_ROLE   = $SCHEMA_FQN || '_FULL_AR';
CALL PLATFORM_DB.RBAC.CREATE_SCHEMA($DB_NAME, $SCHEMA_NAME, $ENV_ABBR);
ALTER SCHEMA IDENTIFIER($SCHEMA_FQN) SET DATA_RETENTION_TIME_IN_DAYS = 14;
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_ANALYST);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_IT_GOVERNANCE);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER);
GRANT DATABASE ROLE IDENTIFIER($RO_ROLE)   TO ROLE IDENTIFIER($R_REPORTER_MARKETING);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_TRANSFORMER);
GRANT DATABASE ROLE IDENTIFIER($FULL_ROLE) TO ROLE IDENTIFIER($R_DATA_LOADER);


-- ============================================================
-- VALIDATION
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);
SHOW SCHEMAS IN DATABASE IDENTIFIER($DB_NAME);
