-- ============================================================
-- MIGRATION - reporting role model (August 2026)
-- RUN PER ENVIRONMENT.  Set ENV_ABBR, then run the whole file.
-- ONE-OFF. Delete this file once DEV, TEST and PROD have all been
-- migrated; 02 / 04 / 05 are the source of truth from then on.
--
-- Brings an environment deployed on 2026-08-07 up to the current
-- 02 / 04 / 05. Four changes:
--
--   1. ADD    13 domain reporter roles + warehouses (real T2 domains
--             from the client's Data Domain Map)
--   2. ADD    {ENV}_POWERBI role + warehouse, and rewire
--             SVC_{ENV}_POWERBI onto it. {ENV}_REPORTER was the Power BI
--             SERVICE role; it is now the HUMAN shared-GOLD role.
--   3. DROP   {ENV}_REPORTER_BILLING / _FINANCE / _MARKETING + warehouses
--   4. DROP   GOLD_BILLING / GOLD_FINANCE / GOLD_MARKETING schemas and
--             their RO/RW/FULL database roles
--
-- Sections 1 and 2 are additive and safe. Sections 3 and 4 DESTROY
-- objects - run section 0 first and read the output.
--
-- Idempotent: CREATE ... IF NOT EXISTS, DROP ... IF EXISTS, and the
-- ALTER USER statements are absolute rather than incremental.
-- ============================================================
SET ENV_ABBR = 'DEV_';                 -- DEV_ | TEST_ | PROD_

SET DB_NAME       = $ENV_ABBR || 'DB';
SET ENV_SYSADMIN  = $ENV_ABBR || 'SYSADMIN';
SET ENV_USERADMIN = $ENV_ABBR || 'USERADMIN';

SET R_ANALYST       = $ENV_ABBR || 'ANALYST';
SET R_TRANSFORMER   = $ENV_ABBR || 'TRANSFORMER';
SET R_DATA_LOADER   = $ENV_ABBR || 'DATA_LOADER';
SET R_DEPLOYER      = $ENV_ABBR || 'DEPLOYER';
SET R_IT_GOVERNANCE = $ENV_ABBR || 'IT_GOVERNANCE';
SET R_REPORTER      = $ENV_ABBR || 'REPORTER';

SET R_POWERBI = $ENV_ABBR || 'POWERBI';
SET W_POWERBI = $ENV_ABBR || 'POWERBI_WH';

SET SVC_PBI_USER = 'SVC_' || $ENV_ABBR || 'POWERBI';

-- roles and warehouses being retired
SET R_OLD_BILLING   = $ENV_ABBR || 'REPORTER_BILLING';
SET W_OLD_BILLING   = $ENV_ABBR || 'REPORTER_BILLING_WH';
SET R_OLD_FINANCE   = $ENV_ABBR || 'REPORTER_FINANCE';
SET W_OLD_FINANCE   = $ENV_ABBR || 'REPORTER_FINANCE_WH';
SET R_OLD_MARKETING = $ENV_ABBR || 'REPORTER_MARKETING';
SET W_OLD_MARKETING = $ENV_ABBR || 'REPORTER_MARKETING_WH';


-- ============================================================
-- 0. PRE-FLIGHT  -  read the output before continuing
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE WAREHOUSE PLATFORM_WH;

-- The three GOLD marts must be EMPTY. If any returns rows, STOP:
-- the BI team has put something there and sections 3-4 would destroy it.
SHOW TABLES IN SCHEMA IDENTIFIER($DB_NAME || '.GOLD_BILLING');
SHOW TABLES IN SCHEMA IDENTIFIER($DB_NAME || '.GOLD_FINANCE');
SHOW TABLES IN SCHEMA IDENTIFIER($DB_NAME || '.GOLD_MARKETING');
SHOW VIEWS  IN SCHEMA IDENTIFIER($DB_NAME || '.GOLD_BILLING');
SHOW VIEWS  IN SCHEMA IDENTIFIER($DB_NAME || '.GOLD_FINANCE');
SHOW VIEWS  IN SCHEMA IDENTIFIER($DB_NAME || '.GOLD_MARKETING');

-- Nobody should be holding the roles about to be dropped. SCIM has
-- provisioned nothing yet, so expect no user grants.
SHOW GRANTS OF ROLE IDENTIFIER($R_OLD_BILLING);
SHOW GRANTS OF ROLE IDENTIFIER($R_OLD_FINANCE);
SHOW GRANTS OF ROLE IDENTIFIER($R_OLD_MARKETING);

-- Current state of the Power BI service user, for comparison after.
DESC USER IDENTIFIER($SVC_PBI_USER);


-- ============================================================
-- 1. ADD  -  13 domain reporter roles
--    Names follow the T2 level of the Data Domain Map.
-- ============================================================
USE ROLE IDENTIFIER($ENV_USERADMIN);

SET R_RPT_SMC_MARKETING_COMMS    = $ENV_ABBR || 'REPORTER_SMC_MARKETING_COMMS';
SET R_RPT_SMC_SALES              = $ENV_ABBR || 'REPORTER_SMC_SALES';
SET R_RPT_FIN_ACCOUNTING         = $ENV_ABBR || 'REPORTER_FIN_ACCOUNTING';
SET R_RPT_FIN_FPNA               = $ENV_ABBR || 'REPORTER_FIN_FPNA';
SET R_RPT_FIN_PROCUREMENT        = $ENV_ABBR || 'REPORTER_FIN_PROCUREMENT';
SET R_RPT_OPE_CUSTOMER_CARE      = $ENV_ABBR || 'REPORTER_OPE_CUSTOMER_CARE';
SET R_RPT_OPE_FIELD_OPERATIONS   = $ENV_ABBR || 'REPORTER_OPE_FIELD_OPERATIONS';
SET R_RPT_HR_PAYROLL             = $ENV_ABBR || 'REPORTER_HR_PAYROLL_PEOPLE_TALENT';
SET R_RPT_HR_HEALTH_SAFETY       = $ENV_ABBR || 'REPORTER_HR_HEALTH_SAFETY';
SET R_RPT_HR_OCCUPATIONAL_HEALTH = $ENV_ABBR || 'REPORTER_HR_OCCUPATIONAL_HEALTH';
SET R_RPT_NET_IT_SECURITY        = $ENV_ABBR || 'REPORTER_NET_IT_SECURITY';
SET R_RPT_NET_NETWORK_OPS        = $ENV_ABBR || 'REPORTER_NET_NETWORK_OPERATIONS';
SET R_RPT_NET_ENGINEERING        = $ENV_ABBR || 'REPORTER_NET_ENGINEERING';

CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_SMC_MARKETING_COMMS);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_SMC_SALES);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_FIN_ACCOUNTING);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_FIN_FPNA);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_FIN_PROCUREMENT);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_HR_PAYROLL);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_HR_HEALTH_SAFETY);
-- Special-category (medical) personal data. Created so the Entra
-- mapping is complete; grant it no schema access until the handling
-- of this data is agreed with Tbaytel's privacy function.
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_NET_IT_SECURITY);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_NET_NETWORK_OPS);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_RPT_NET_ENGINEERING);

GRANT ROLE IDENTIFIER($R_RPT_SMC_MARKETING_COMMS)    TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_SMC_SALES)              TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_FIN_ACCOUNTING)         TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_FIN_FPNA)               TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_FIN_PROCUREMENT)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE)      TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS)   TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_HR_PAYROLL)             TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_HR_HEALTH_SAFETY)       TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH) TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_NET_IT_SECURITY)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_NET_NETWORK_OPS)        TO ROLE IDENTIFIER($ENV_SYSADMIN);
GRANT ROLE IDENTIFIER($R_RPT_NET_ENGINEERING)        TO ROLE IDENTIFIER($ENV_SYSADMIN);


-- ------------------------------------------------------------
-- 13 warehouses, one per role. X-Small, suspended, no cost idle.
-- ------------------------------------------------------------
USE ROLE IDENTIFIER($ENV_SYSADMIN);

SET W_RPT_SMC_MARKETING_COMMS    = $ENV_ABBR || 'REPORTER_SMC_MARKETING_COMMS_WH';
SET W_RPT_SMC_SALES              = $ENV_ABBR || 'REPORTER_SMC_SALES_WH';
SET W_RPT_FIN_ACCOUNTING         = $ENV_ABBR || 'REPORTER_FIN_ACCOUNTING_WH';
SET W_RPT_FIN_FPNA               = $ENV_ABBR || 'REPORTER_FIN_FPNA_WH';
SET W_RPT_FIN_PROCUREMENT        = $ENV_ABBR || 'REPORTER_FIN_PROCUREMENT_WH';
SET W_RPT_OPE_CUSTOMER_CARE      = $ENV_ABBR || 'REPORTER_OPE_CUSTOMER_CARE_WH';
SET W_RPT_OPE_FIELD_OPERATIONS   = $ENV_ABBR || 'REPORTER_OPE_FIELD_OPERATIONS_WH';
SET W_RPT_HR_PAYROLL             = $ENV_ABBR || 'REPORTER_HR_PAYROLL_PEOPLE_TALENT_WH';
SET W_RPT_HR_HEALTH_SAFETY       = $ENV_ABBR || 'REPORTER_HR_HEALTH_SAFETY_WH';
SET W_RPT_HR_OCCUPATIONAL_HEALTH = $ENV_ABBR || 'REPORTER_HR_OCCUPATIONAL_HEALTH_WH';
SET W_RPT_NET_IT_SECURITY        = $ENV_ABBR || 'REPORTER_NET_IT_SECURITY_WH';
SET W_RPT_NET_NETWORK_OPS        = $ENV_ABBR || 'REPORTER_NET_NETWORK_OPERATIONS_WH';
SET W_RPT_NET_ENGINEERING        = $ENV_ABBR || 'REPORTER_NET_ENGINEERING_WH';

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_SMC_MARKETING_COMMS)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_SMC_SALES)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_FIN_ACCOUNTING)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_FIN_FPNA)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_FIN_PROCUREMENT)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_OPE_CUSTOMER_CARE)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_OPE_FIELD_OPERATIONS)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_HR_PAYROLL)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_HR_HEALTH_SAFETY)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_HR_OCCUPATIONAL_HEALTH)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_NET_IT_SECURITY)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_NET_NETWORK_OPS)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_RPT_NET_ENGINEERING)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_SMC_MARKETING_COMMS)    TO ROLE IDENTIFIER($R_RPT_SMC_MARKETING_COMMS);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_SMC_SALES)              TO ROLE IDENTIFIER($R_RPT_SMC_SALES);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_FIN_ACCOUNTING)         TO ROLE IDENTIFIER($R_RPT_FIN_ACCOUNTING);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_FIN_FPNA)               TO ROLE IDENTIFIER($R_RPT_FIN_FPNA);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_FIN_PROCUREMENT)        TO ROLE IDENTIFIER($R_RPT_FIN_PROCUREMENT);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_OPE_CUSTOMER_CARE)      TO ROLE IDENTIFIER($R_RPT_OPE_CUSTOMER_CARE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_OPE_FIELD_OPERATIONS)   TO ROLE IDENTIFIER($R_RPT_OPE_FIELD_OPERATIONS);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_HR_PAYROLL)             TO ROLE IDENTIFIER($R_RPT_HR_PAYROLL);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_HR_HEALTH_SAFETY)       TO ROLE IDENTIFIER($R_RPT_HR_HEALTH_SAFETY);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_HR_OCCUPATIONAL_HEALTH) TO ROLE IDENTIFIER($R_RPT_HR_OCCUPATIONAL_HEALTH);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_NET_IT_SECURITY)        TO ROLE IDENTIFIER($R_RPT_NET_IT_SECURITY);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_NET_NETWORK_OPS)        TO ROLE IDENTIFIER($R_RPT_NET_NETWORK_OPS);
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_RPT_NET_ENGINEERING)        TO ROLE IDENTIFIER($R_RPT_NET_ENGINEERING);

-- No schema grants: a domain role gets access when its GOLD_{domain}
-- mart is built. See the pattern at the end of 04.


-- ============================================================
-- 2. ADD  -  {ENV}_POWERBI and rewire the service user
--    {ENV}_REPORTER keeps existing, but becomes the HUMAN role for
--    the shared GOLD schema. Its grants on GOLD are already correct.
-- ============================================================
USE ROLE IDENTIFIER($ENV_USERADMIN);
CREATE ROLE IF NOT EXISTS IDENTIFIER($R_POWERBI);
GRANT ROLE IDENTIFIER($R_POWERBI) TO ROLE IDENTIFIER($ENV_SYSADMIN);

USE ROLE IDENTIFIER($ENV_SYSADMIN);
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($W_POWERBI)
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE IDENTIFIER($W_POWERBI) TO ROLE IDENTIFIER($R_POWERBI);

-- Read on the shared GOLD schema.
SET GOLD_RO = $DB_NAME || '.GOLD_RO_AR';
GRANT DATABASE ROLE IDENTIFIER($GOLD_RO) TO ROLE IDENTIFIER($R_POWERBI);

-- Rewire SVC_{ENV}_POWERBI. CREATE USER IF NOT EXISTS in 05 does not
-- update an existing user, so these have to be explicit.
USE ROLE IDENTIFIER($ENV_USERADMIN);
GRANT ROLE IDENTIFIER($R_POWERBI) TO USER IDENTIFIER($SVC_PBI_USER);
ALTER USER IDENTIFIER($SVC_PBI_USER) SET
    DEFAULT_ROLE      = $R_POWERBI,
    DEFAULT_WAREHOUSE = $W_POWERBI;

-- Remove the old role from the service user LAST, so the user is never
-- left without a working role.
REVOKE ROLE IDENTIFIER($R_REPORTER) FROM USER IDENTIFIER($SVC_PBI_USER);


-- ============================================================
-- 3. DROP  -  the three placeholder domain reporter roles
--    Destructive. Section 0 must have shown no user grants.
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);
DROP WAREHOUSE IF EXISTS IDENTIFIER($W_OLD_BILLING);
DROP WAREHOUSE IF EXISTS IDENTIFIER($W_OLD_FINANCE);
DROP WAREHOUSE IF EXISTS IDENTIFIER($W_OLD_MARKETING);

USE ROLE IDENTIFIER($ENV_USERADMIN);
DROP ROLE IF EXISTS IDENTIFIER($R_OLD_BILLING);
DROP ROLE IF EXISTS IDENTIFIER($R_OLD_FINANCE);
DROP ROLE IF EXISTS IDENTIFIER($R_OLD_MARKETING);


-- ============================================================
-- 4. DROP  -  the three placeholder GOLD marts
--    DROP_SCHEMA removes the schema AND its RO/RW/FULL database roles.
--    It refuses if the schema does not exist, and returns a message
--    rather than raising - read the result of each call.
--    Destructive. Section 0 must have shown these schemas empty.
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);
USE DATABASE PLATFORM_DB;
USE SCHEMA RBAC;

CALL PLATFORM_DB.RBAC.DROP_SCHEMA($DB_NAME, 'GOLD_BILLING');
CALL PLATFORM_DB.RBAC.DROP_SCHEMA($DB_NAME, 'GOLD_FINANCE');
CALL PLATFORM_DB.RBAC.DROP_SCHEMA($DB_NAME, 'GOLD_MARKETING');


-- ============================================================
-- 5. VALIDATION
-- ============================================================
USE ROLE IDENTIFIER($ENV_SYSADMIN);

-- Expect 20 roles: 4 human + 13 domain reporters + 3 service.
-- The three _BILLING / _FINANCE / _MARKETING roles must be gone.
SHOW ROLES LIKE $ENV_ABBR || '%';

-- Expect 20 warehouses, same rule.
SHOW WAREHOUSES LIKE $ENV_ABBR || '%';

-- Expect 6 schemas: ADM, RAW, BRONZE, BRONZE_HIST, SILVER, GOLD.
SHOW SCHEMAS IN DATABASE IDENTIFIER($DB_NAME);

-- Expect DEFAULT_ROLE {ENV}_POWERBI and DEFAULT_WAREHOUSE
-- {ENV}_POWERBI_WH.
DESC USER IDENTIFIER($SVC_PBI_USER);

-- Expect {ENV}_POWERBI only - {ENV}_REPORTER must no longer be here.
SHOW GRANTS TO USER IDENTIFIER($SVC_PBI_USER);

-- Orphan check: no database role should remain for a dropped schema.
SHOW DATABASE ROLES IN DATABASE IDENTIFIER($DB_NAME);
